// <auto-generated />
using System;
using BookMarketplace.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookMarketplace.DAL.Migrations
{
    [DbContext(typeof(BookMarketplaceDbContext))]
    [Migration("20260503172828_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookMarketplace.Model.DrustvenaIgra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxBrojIgraca")
                        .HasColumnType("int");

                    b.Property<int>("MinBrojIgraca")
                        .HasColumnType("int");

                    b.Property<int>("MinimalnasDob")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OglasId")
                        .HasColumnType("int");

                    b.Property<int>("TrajanjeMins")
                        .HasColumnType("int");

                    b.Property<int>("Zanr")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OglasId")
                        .IsUnique();

                    b.ToTable("DrustveneIgre");
                });

            modelBuilder.Entity("BookMarketplace.Model.Favorit", b =>
                {
                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("OglasId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumDodavanja")
                        .HasColumnType("datetime2");

                    b.HasKey("KorisnikId", "OglasId");

                    b.HasIndex("OglasId");

                    b.ToTable("Favoriti");
                });

            modelBuilder.Entity("BookMarketplace.Model.Grad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostanskiBroj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gradovi");
                });

            modelBuilder.Entity("BookMarketplace.Model.Knjiga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GodinaIzdanja")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Izdavac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jezik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OglasId")
                        .HasColumnType("int");

                    b.Property<int>("Zanr")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OglasId")
                        .IsUnique();

                    b.ToTable("Knjige");
                });

            modelBuilder.Entity("BookMarketplace.Model.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeIPrezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("BookMarketplace.Model.Oglas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<int>("GradId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StanjeArtikla")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipOglasa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Oglasi");
                });

            modelBuilder.Entity("BookMarketplace.Model.Poruka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumSlanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("OglasId")
                        .HasColumnType("int");

                    b.Property<int>("PosiljateljId")
                        .HasColumnType("int");

                    b.Property<int>("PrimateljId")
                        .HasColumnType("int");

                    b.Property<bool>("Procitano")
                        .HasColumnType("bit");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OglasId");

                    b.HasIndex("PosiljateljId");

                    b.HasIndex("PrimateljId");

                    b.ToTable("Poruke");
                });

            modelBuilder.Entity("BookMarketplace.Model.Slika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OglasId")
                        .HasColumnType("int");

                    b.Property<string>("Putanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RedoslijedPrikaza")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OglasId");

                    b.ToTable("Slike");
                });

            modelBuilder.Entity("BookMarketplace.Model.DrustvenaIgra", b =>
                {
                    b.HasOne("BookMarketplace.Model.Oglas", "Oglas")
                        .WithOne("DrustvenaIgra")
                        .HasForeignKey("BookMarketplace.Model.DrustvenaIgra", "OglasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oglas");
                });

            modelBuilder.Entity("BookMarketplace.Model.Favorit", b =>
                {
                    b.HasOne("BookMarketplace.Model.Korisnik", "Korisnik")
                        .WithMany("Favoriti")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookMarketplace.Model.Oglas", "Oglas")
                        .WithMany("Favoriti")
                        .HasForeignKey("OglasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Oglas");
                });

            modelBuilder.Entity("BookMarketplace.Model.Knjiga", b =>
                {
                    b.HasOne("BookMarketplace.Model.Oglas", "Oglas")
                        .WithOne("Knjiga")
                        .HasForeignKey("BookMarketplace.Model.Knjiga", "OglasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oglas");
                });

            modelBuilder.Entity("BookMarketplace.Model.Oglas", b =>
                {
                    b.HasOne("BookMarketplace.Model.Grad", "Grad")
                        .WithMany("Oglasi")
                        .HasForeignKey("GradId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookMarketplace.Model.Korisnik", "Korisnik")
                        .WithMany("Oglasi")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grad");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("BookMarketplace.Model.Poruka", b =>
                {
                    b.HasOne("BookMarketplace.Model.Oglas", "Oglas")
                        .WithMany("Poruke")
                        .HasForeignKey("OglasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookMarketplace.Model.Korisnik", "Posiljatelj")
                        .WithMany("PoslanePoruke")
                        .HasForeignKey("PosiljateljId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookMarketplace.Model.Korisnik", "Primatelj")
                        .WithMany("PrimljenePoruke")
                        .HasForeignKey("PrimateljId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Oglas");

                    b.Navigation("Posiljatelj");

                    b.Navigation("Primatelj");
                });

            modelBuilder.Entity("BookMarketplace.Model.Slika", b =>
                {
                    b.HasOne("BookMarketplace.Model.Oglas", "Oglas")
                        .WithMany("Slike")
                        .HasForeignKey("OglasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oglas");
                });

            modelBuilder.Entity("BookMarketplace.Model.Grad", b =>
                {
                    b.Navigation("Oglasi");
                });

            modelBuilder.Entity("BookMarketplace.Model.Korisnik", b =>
                {
                    b.Navigation("Favoriti");

                    b.Navigation("Oglasi");

                    b.Navigation("PoslanePoruke");

                    b.Navigation("PrimljenePoruke");
                });

            modelBuilder.Entity("BookMarketplace.Model.Oglas", b =>
                {
                    b.Navigation("DrustvenaIgra");

                    b.Navigation("Favoriti");

                    b.Navigation("Knjiga");

                    b.Navigation("Poruke");

                    b.Navigation("Slike");
                });
#pragma warning restore 612, 618
        }
    }
}
