// <auto-generated />
using System;
using BookMarketplace.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookMarketplace.DAL.Migrations
{
    [DbContext(typeof(BookMarketplaceDbContext))]
    [Migration("20260520174754_AddDatumIstekaToOglas")]
    partial class AddDatumIstekaToOglas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookMarketplace.Model.DrustvenaIgra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxBrojIgraca")
                        .HasColumnType("int");

                    b.Property<int>("MinBrojIgraca")
                        .HasColumnType("int");

                    b.Property<int>("MinimalnasDob")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OglasId")
                        .HasColumnType("int");

                    b.Property<int>("TrajanjeMins")
                        .HasColumnType("int");

                    b.Property<int>("Zanr")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OglasId")
                        .IsUnique();

                    b.ToTable("DrustveneIgre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxBrojIgraca = 4,
                            MinBrojIgraca = 3,
                            MinimalnasDob = 10,
                            Naziv = "Catan - Osnovna igra",
                            OglasId = 2,
                            TrajanjeMins = 75,
                            Zanr = 0
                        },
                        new
                        {
                            Id = 2,
                            MaxBrojIgraca = 5,
                            MinBrojIgraca = 2,
                            MinimalnasDob = 8,
                            Naziv = "Ticket to Ride: Europa",
                            OglasId = 4,
                            TrajanjeMins = 60,
                            Zanr = 0
                        },
                        new
                        {
                            Id = 3,
                            MaxBrojIgraca = 5,
                            MinBrojIgraca = 1,
                            MinimalnasDob = 10,
                            Naziv = "Wingspan",
                            OglasId = 6,
                            TrajanjeMins = 90,
                            Zanr = 0
                        },
                        new
                        {
                            Id = 4,
                            MaxBrojIgraca = 6,
                            MinBrojIgraca = 3,
                            MinimalnasDob = 8,
                            Naziv = "Dixit",
                            OglasId = 8,
                            TrajanjeMins = 30,
                            Zanr = 4
                        },
                        new
                        {
                            Id = 5,
                            MaxBrojIgraca = 4,
                            MinBrojIgraca = 2,
                            MinimalnasDob = 8,
                            Naziv = "Pandemic",
                            OglasId = 10,
                            TrajanjeMins = 45,
                            Zanr = 1
                        },
                        new
                        {
                            Id = 6,
                            MaxBrojIgraca = 7,
                            MinBrojIgraca = 2,
                            MinimalnasDob = 10,
                            Naziv = "7 Wonders",
                            OglasId = 16,
                            TrajanjeMins = 30,
                            Zanr = 0
                        },
                        new
                        {
                            Id = 7,
                            MaxBrojIgraca = 8,
                            MinBrojIgraca = 2,
                            MinimalnasDob = 10,
                            Naziv = "Codenames",
                            OglasId = 17,
                            TrajanjeMins = 15,
                            Zanr = 4
                        },
                        new
                        {
                            Id = 8,
                            MaxBrojIgraca = 4,
                            MinBrojIgraca = 2,
                            MinimalnasDob = 8,
                            Naziv = "Azul",
                            OglasId = 18,
                            TrajanjeMins = 45,
                            Zanr = 3
                        },
                        new
                        {
                            Id = 9,
                            MaxBrojIgraca = 5,
                            MinBrojIgraca = 2,
                            MinimalnasDob = 7,
                            Naziv = "Exploding Kittens",
                            OglasId = 19,
                            TrajanjeMins = 15,
                            Zanr = 4
                        },
                        new
                        {
                            Id = 10,
                            MaxBrojIgraca = 8,
                            MinBrojIgraca = 2,
                            MinimalnasDob = 6,
                            Naziv = "Dobble",
                            OglasId = 20,
                            TrajanjeMins = 10,
                            Zanr = 4
                        });
                });

            modelBuilder.Entity("BookMarketplace.Model.Favorit", b =>
                {
                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("OglasId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumDodavanja")
                        .HasColumnType("datetime2");

                    b.HasKey("KorisnikId", "OglasId");

                    b.HasIndex("OglasId");

                    b.ToTable("Favoriti");
                });

            modelBuilder.Entity("BookMarketplace.Model.Grad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostanskiBroj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gradovi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Zagreb",
                            PostanskiBroj = "10000"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Split",
                            PostanskiBroj = "21000"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Rijeka",
                            PostanskiBroj = "51000"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Osijek",
                            PostanskiBroj = "31000"
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "Zadar",
                            PostanskiBroj = "23000"
                        },
                        new
                        {
                            Id = 6,
                            Naziv = "Pula",
                            PostanskiBroj = "52100"
                        },
                        new
                        {
                            Id = 7,
                            Naziv = "Dubrovnik",
                            PostanskiBroj = "20000"
                        },
                        new
                        {
                            Id = 8,
                            Naziv = "Varaždin",
                            PostanskiBroj = "42000"
                        },
                        new
                        {
                            Id = 9,
                            Naziv = "Šibenik",
                            PostanskiBroj = "22000"
                        },
                        new
                        {
                            Id = 10,
                            Naziv = "Slavonski Brod",
                            PostanskiBroj = "35000"
                        });
                });

            modelBuilder.Entity("BookMarketplace.Model.Knjiga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrojStrana")
                        .HasColumnType("int");

                    b.Property<int>("GodinaIzdanja")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Izdavac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jezik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OglasId")
                        .HasColumnType("int");

                    b.Property<int>("Zanr")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OglasId")
                        .IsUnique();

                    b.ToTable("Knjige");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "J.K. Rowling",
                            BrojStrana = 320,
                            GodinaIzdanja = 2007,
                            ISBN = "978-0545010221",
                            Izdavac = "Scholastic",
                            Jezik = "Engleski",
                            Naziv = "Harry Potter i Kamen mudraca",
                            OglasId = 1,
                            Zanr = 0
                        },
                        new
                        {
                            Id = 2,
                            Autor = "George R.R. Martin",
                            BrojStrana = 694,
                            GodinaIzdanja = 1996,
                            ISBN = "978-0553103540",
                            Izdavac = "Bantam Books",
                            Jezik = "Engleski",
                            Naziv = "Igra prijestolja",
                            OglasId = 11,
                            Zanr = 0
                        },
                        new
                        {
                            Id = 3,
                            Autor = "Agatha Christie",
                            BrojStrana = 256,
                            GodinaIzdanja = 1934,
                            ISBN = "978-0062073488",
                            Izdavac = "HarperCollins",
                            Jezik = "Engleski",
                            Naziv = "Ubojstvo u Orijent Expressu",
                            OglasId = 7,
                            Zanr = 4
                        },
                        new
                        {
                            Id = 4,
                            Autor = "Dan Brown",
                            BrojStrana = 489,
                            GodinaIzdanja = 2003,
                            ISBN = "978-0307474278",
                            Izdavac = "Doubleday",
                            Jezik = "Engleski",
                            Naziv = "Da Vincijev kod",
                            OglasId = 12,
                            Zanr = 1
                        },
                        new
                        {
                            Id = 5,
                            Autor = "Jane Austen",
                            BrojStrana = 279,
                            GodinaIzdanja = 1813,
                            ISBN = "978-1503290563",
                            Izdavac = "CreateSpace Independent Publishing Platform",
                            Jezik = "Engleski",
                            Naziv = "Ponos i predrasude",
                            OglasId = 5,
                            Zanr = 2
                        },
                        new
                        {
                            Id = 6,
                            Autor = "Isaac Asimov",
                            BrojStrana = 255,
                            GodinaIzdanja = 1950,
                            ISBN = "978-0553293357",
                            Izdavac = "Bantam Books",
                            Jezik = "Engleski",
                            Naziv = "Fondacija",
                            OglasId = 13,
                            Zanr = 3
                        },
                        new
                        {
                            Id = 7,
                            Autor = "Frank Herbert",
                            BrojStrana = 412,
                            GodinaIzdanja = 1965,
                            ISBN = "978-0441013593",
                            Izdavac = "Ace Books",
                            Jezik = "Engleski",
                            Naziv = "Dune",
                            OglasId = 3,
                            Zanr = 3
                        },
                        new
                        {
                            Id = 8,
                            Autor = "Antoine de Saint-Exupéry",
                            BrojStrana = 96,
                            GodinaIzdanja = 1943,
                            ISBN = "978-0156012195",
                            Izdavac = "Harcourt",
                            Jezik = "Hrvatski",
                            Naziv = "Mali princ",
                            OglasId = 14,
                            Zanr = 5
                        },
                        new
                        {
                            Id = 9,
                            Autor = "Gabriel García Márquez",
                            BrojStrana = 417,
                            GodinaIzdanja = 1967,
                            ISBN = "978-0060883287",
                            Izdavac = "Harper & Row",
                            Jezik = "Hrvatski",
                            Naziv = "Sto godina samoće",
                            OglasId = 9,
                            Zanr = 2
                        },
                        new
                        {
                            Id = 10,
                            Autor = "Arthur Conan Doyle",
                            BrojStrana = 256,
                            GodinaIzdanja = 1902,
                            ISBN = "978-0141034355",
                            Izdavac = "Penguin Classics",
                            Jezik = "Engleski",
                            Naziv = "Pas Baskervillea",
                            OglasId = 15,
                            Zanr = 4
                        });
                });

            modelBuilder.Entity("BookMarketplace.Model.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeIPrezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumRegistracije = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana.anic@email.com",
                            ImeIPrezime = "Ana Anić",
                            Lozinka = "lozinka123",
                            Telefon = "091-234-5678",
                            Uloga = 0
                        },
                        new
                        {
                            Id = 2,
                            DatumRegistracije = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pero.peric@email.com",
                            ImeIPrezime = "Pero Perić",
                            Lozinka = "lozinka456",
                            Telefon = "092-345-6789",
                            Uloga = 0
                        },
                        new
                        {
                            Id = 3,
                            DatumRegistracije = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maja.majic@email.com",
                            ImeIPrezime = "Maja Majić",
                            Lozinka = "lozinka789",
                            Telefon = "095-456-7890",
                            Uloga = 0
                        },
                        new
                        {
                            Id = 4,
                            DatumRegistracije = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivan.ivic@email.com",
                            ImeIPrezime = "Ivan Ivić",
                            Lozinka = "lozinka321",
                            Telefon = "093-567-8901",
                            Uloga = 0
                        },
                        new
                        {
                            Id = 5,
                            DatumRegistracije = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marko.markovic@email.com",
                            ImeIPrezime = "Marko Marković",
                            Lozinka = "lozinka654",
                            Telefon = "091-678-9012",
                            Uloga = 0
                        },
                        new
                        {
                            Id = 6,
                            DatumRegistracije = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivana.horvat@email.com",
                            ImeIPrezime = "Ivana Horvat",
                            Lozinka = "lozinka987",
                            Telefon = "092-789-0123",
                            Uloga = 0
                        },
                        new
                        {
                            Id = 7,
                            DatumRegistracije = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tomislav.tomic@email.com",
                            ImeIPrezime = "Tomislav Tomić",
                            Lozinka = "admin001",
                            Telefon = "095-890-1234",
                            Uloga = 1
                        },
                        new
                        {
                            Id = 8,
                            DatumRegistracije = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucija.lukic@email.com",
                            ImeIPrezime = "Lucija Lukić",
                            Lozinka = "lozinka111",
                            Telefon = "099-901-2345",
                            Uloga = 0
                        },
                        new
                        {
                            Id = 9,
                            DatumRegistracije = new DateTime(2024, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "stjepan.stjepic@email.com",
                            ImeIPrezime = "Stjepan Stjepić",
                            Lozinka = "lozinka222",
                            Telefon = "091-012-3456",
                            Uloga = 0
                        },
                        new
                        {
                            Id = 10,
                            DatumRegistracije = new DateTime(2024, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "petra.petric@email.com",
                            ImeIPrezime = "Petra Petrić",
                            Lozinka = "lozinka333",
                            Telefon = "092-123-4567",
                            Uloga = 0
                        });
                });

            modelBuilder.Entity("BookMarketplace.Model.Oglas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DatumIsteka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<int>("GradId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StanjeArtikla")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipOglasa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Oglasi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 15.00m,
                            DatumObjave = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 1,
                            KorisnikId = 1,
                            Naslov = "Harry Potter i Kamen mudraca",
                            Opis = "Knjiga u odličnom stanju, čitana jednom.",
                            StanjeArtikla = 1,
                            Status = 0,
                            TipOglasa = 0
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 45.00m,
                            DatumObjave = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 1,
                            KorisnikId = 1,
                            Naslov = "Catan - Osnovna igra",
                            Opis = "Kompletna igra, sve kartice i figurice na broju.",
                            StanjeArtikla = 2,
                            Status = 0,
                            TipOglasa = 1
                        },
                        new
                        {
                            Id = 3,
                            Cijena = 10.00m,
                            DatumObjave = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 1,
                            KorisnikId = 1,
                            Naslov = "Dune",
                            Opis = "Klasik znanstvene fantastike, malo požutjele stranice.",
                            StanjeArtikla = 3,
                            Status = 0,
                            TipOglasa = 0
                        },
                        new
                        {
                            Id = 4,
                            Cijena = 55.00m,
                            DatumObjave = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 2,
                            KorisnikId = 2,
                            Naslov = "Ticket to Ride: Europa",
                            Opis = "Popularna strategijska igra, igrana samo 3 puta.",
                            StanjeArtikla = 1,
                            Status = 0,
                            TipOglasa = 1
                        },
                        new
                        {
                            Id = 5,
                            Cijena = 8.00m,
                            DatumObjave = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 2,
                            KorisnikId = 2,
                            Naslov = "1984",
                            Opis = "George Orwell, distopijski roman, dobro stanje.",
                            StanjeArtikla = 2,
                            Status = 0,
                            TipOglasa = 0
                        },
                        new
                        {
                            Id = 6,
                            Cijena = 70.00m,
                            DatumIzmjene = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumObjave = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 2,
                            KorisnikId = 2,
                            Naslov = "Wingspan",
                            Opis = "Igra o pticama, kompletna s ekspanzijom.",
                            StanjeArtikla = 1,
                            Status = 1,
                            TipOglasa = 1
                        },
                        new
                        {
                            Id = 7,
                            Cijena = 12.00m,
                            DatumObjave = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 3,
                            KorisnikId = 3,
                            Naslov = "Ubojstvo u Orijent Expressu",
                            Opis = "Agatha Christie, kao novo.",
                            StanjeArtikla = 1,
                            Status = 0,
                            TipOglasa = 0
                        },
                        new
                        {
                            Id = 8,
                            Cijena = 30.00m,
                            DatumObjave = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 3,
                            KorisnikId = 3,
                            Naslov = "Dixit",
                            Opis = "Kreativna igra asocijacija, perfektno stanje.",
                            StanjeArtikla = 0,
                            Status = 0,
                            TipOglasa = 1
                        },
                        new
                        {
                            Id = 9,
                            Cijena = 20.00m,
                            DatumObjave = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 3,
                            KorisnikId = 3,
                            Naslov = "Gospodar prstenova: Prstenova družina",
                            Opis = "Tolkien klasik, tvrdi uvez.",
                            StanjeArtikla = 2,
                            Status = 2,
                            TipOglasa = 0
                        },
                        new
                        {
                            Id = 10,
                            Cijena = 40.00m,
                            DatumObjave = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 4,
                            KorisnikId = 4,
                            Naslov = "Pandemic - igra suradnje",
                            Opis = "Kooperativna igra za cijelu obitelj, komplet u odličnom stanju.",
                            StanjeArtikla = 1,
                            Status = 0,
                            TipOglasa = 1
                        },
                        new
                        {
                            Id = 11,
                            Cijena = 18.00m,
                            DatumObjave = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 4,
                            KorisnikId = 4,
                            Naslov = "Igra prijestolja",
                            Opis = "George R.R. Martin, eng. izdanje, tvrdi uvez.",
                            StanjeArtikla = 2,
                            Status = 0,
                            TipOglasa = 0
                        },
                        new
                        {
                            Id = 12,
                            Cijena = 14.00m,
                            DatumObjave = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 5,
                            KorisnikId = 5,
                            Naslov = "Da Vincijev kod",
                            Opis = "Dan Brown, uzbudljiv triler, čitana jednom.",
                            StanjeArtikla = 1,
                            Status = 0,
                            TipOglasa = 0
                        },
                        new
                        {
                            Id = 13,
                            Cijena = 11.00m,
                            DatumObjave = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 5,
                            KorisnikId = 5,
                            Naslov = "Fondacija",
                            Opis = "Isaac Asimov, klasik znanstvene fantastike, meki uvez.",
                            StanjeArtikla = 2,
                            Status = 0,
                            TipOglasa = 0
                        },
                        new
                        {
                            Id = 14,
                            Cijena = 9.00m,
                            DatumObjave = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 6,
                            KorisnikId = 6,
                            Naslov = "Mali princ",
                            Opis = "Saint-Exupéry, hrvatsko izdanje, ilustrirano.",
                            StanjeArtikla = 1,
                            Status = 0,
                            TipOglasa = 0
                        },
                        new
                        {
                            Id = 15,
                            Cijena = 10.00m,
                            DatumObjave = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 6,
                            KorisnikId = 6,
                            Naslov = "Pas Baskervillea",
                            Opis = "Sherlock Holmes klasik, eng. izdanje.",
                            StanjeArtikla = 3,
                            Status = 0,
                            TipOglasa = 0
                        },
                        new
                        {
                            Id = 16,
                            Cijena = 35.00m,
                            DatumObjave = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 7,
                            KorisnikId = 7,
                            Naslov = "7 Wonders",
                            Opis = "Strateška igra za 2-7 igrača, kompletna.",
                            StanjeArtikla = 2,
                            Status = 0,
                            TipOglasa = 1
                        },
                        new
                        {
                            Id = 17,
                            Cijena = 22.00m,
                            DatumObjave = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 7,
                            KorisnikId = 7,
                            Naslov = "Codenames",
                            Opis = "Zabavna igra za veće grupe, sve karte na broju.",
                            StanjeArtikla = 1,
                            Status = 0,
                            TipOglasa = 1
                        },
                        new
                        {
                            Id = 18,
                            Cijena = 38.00m,
                            DatumObjave = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 8,
                            KorisnikId = 8,
                            Naslov = "Azul",
                            Opis = "Prekrasna apstraktna igra, pločice u savršenom stanju.",
                            StanjeArtikla = 0,
                            Status = 0,
                            TipOglasa = 1
                        },
                        new
                        {
                            Id = 19,
                            Cijena = 18.00m,
                            DatumObjave = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 8,
                            KorisnikId = 8,
                            Naslov = "Exploding Kittens",
                            Opis = "Brza i smiješna kartaška igra, kompletna.",
                            StanjeArtikla = 2,
                            Status = 0,
                            TipOglasa = 1
                        },
                        new
                        {
                            Id = 20,
                            Cijena = 15.00m,
                            DatumObjave = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradId = 9,
                            KorisnikId = 9,
                            Naslov = "Dobble",
                            Opis = "Igra brzog zapažanja, idealna za djecu i odrasle.",
                            StanjeArtikla = 1,
                            Status = 0,
                            TipOglasa = 1
                        });
                });

            modelBuilder.Entity("BookMarketplace.Model.Poruka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumSlanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("OglasId")
                        .HasColumnType("int");

                    b.Property<int>("PosiljateljId")
                        .HasColumnType("int");

                    b.Property<int>("PrimateljId")
                        .HasColumnType("int");

                    b.Property<bool>("Procitano")
                        .HasColumnType("bit");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OglasId");

                    b.HasIndex("PosiljateljId");

                    b.HasIndex("PrimateljId");

                    b.ToTable("Poruke");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumSlanja = new DateTime(2025, 1, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            OglasId = 1,
                            PosiljateljId = 2,
                            PrimateljId = 1,
                            Procitano = true,
                            Sadrzaj = "Je li knjiga još dostupna?"
                        },
                        new
                        {
                            Id = 2,
                            DatumSlanja = new DateTime(2025, 1, 12, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            OglasId = 1,
                            PosiljateljId = 1,
                            PrimateljId = 2,
                            Procitano = false,
                            Sadrzaj = "Da, slobodno mi se javi za preuzimanje!"
                        },
                        new
                        {
                            Id = 3,
                            DatumSlanja = new DateTime(2025, 1, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OglasId = 2,
                            PosiljateljId = 3,
                            PrimateljId = 1,
                            Procitano = false,
                            Sadrzaj = "Može li niža cijena za Catan?"
                        },
                        new
                        {
                            Id = 4,
                            DatumSlanja = new DateTime(2025, 1, 21, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            OglasId = 4,
                            PosiljateljId = 3,
                            PrimateljId = 2,
                            Procitano = true,
                            Sadrzaj = "Koliko dugo igra traje?"
                        },
                        new
                        {
                            Id = 5,
                            DatumSlanja = new DateTime(2025, 1, 21, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OglasId = 4,
                            PosiljateljId = 2,
                            PrimateljId = 3,
                            Procitano = false,
                            Sadrzaj = "Oko 60 minuta prosječno."
                        },
                        new
                        {
                            Id = 6,
                            DatumSlanja = new DateTime(2025, 2, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OglasId = 6,
                            PosiljateljId = 1,
                            PrimateljId = 2,
                            Procitano = true,
                            Sadrzaj = "Je li Wingspan kompletna s pravilima?"
                        },
                        new
                        {
                            Id = 7,
                            DatumSlanja = new DateTime(2025, 2, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OglasId = 6,
                            PosiljateljId = 2,
                            PrimateljId = 1,
                            Procitano = false,
                            Sadrzaj = "Da, sve je kompletno uključujući ekspanziju."
                        },
                        new
                        {
                            Id = 8,
                            DatumSlanja = new DateTime(2025, 3, 6, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            OglasId = 8,
                            PosiljateljId = 1,
                            PrimateljId = 3,
                            Procitano = false,
                            Sadrzaj = "Može li se dogovoriti dostava za Dixit?"
                        },
                        new
                        {
                            Id = 9,
                            DatumSlanja = new DateTime(2025, 3, 12, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            OglasId = 9,
                            PosiljateljId = 3,
                            PrimateljId = 2,
                            Procitano = true,
                            Sadrzaj = "Imam još jednu kopiju Tolkiena, zanima li te?"
                        },
                        new
                        {
                            Id = 10,
                            DatumSlanja = new DateTime(2025, 3, 12, 19, 45, 0, 0, DateTimeKind.Unspecified),
                            OglasId = 9,
                            PosiljateljId = 2,
                            PrimateljId = 3,
                            Procitano = false,
                            Sadrzaj = "Hvala, ali već sam nabavio."
                        });
                });

            modelBuilder.Entity("BookMarketplace.Model.Slika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OglasId")
                        .HasColumnType("int");

                    b.Property<string>("Putanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RedoslijedPrikaza")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OglasId");

                    b.ToTable("Slike");
                });

            modelBuilder.Entity("BookMarketplace.Model.DrustvenaIgra", b =>
                {
                    b.HasOne("BookMarketplace.Model.Oglas", "Oglas")
                        .WithOne("DrustvenaIgra")
                        .HasForeignKey("BookMarketplace.Model.DrustvenaIgra", "OglasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oglas");
                });

            modelBuilder.Entity("BookMarketplace.Model.Favorit", b =>
                {
                    b.HasOne("BookMarketplace.Model.Korisnik", "Korisnik")
                        .WithMany("Favoriti")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookMarketplace.Model.Oglas", "Oglas")
                        .WithMany("Favoriti")
                        .HasForeignKey("OglasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Oglas");
                });

            modelBuilder.Entity("BookMarketplace.Model.Knjiga", b =>
                {
                    b.HasOne("BookMarketplace.Model.Oglas", "Oglas")
                        .WithOne("Knjiga")
                        .HasForeignKey("BookMarketplace.Model.Knjiga", "OglasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oglas");
                });

            modelBuilder.Entity("BookMarketplace.Model.Oglas", b =>
                {
                    b.HasOne("BookMarketplace.Model.Grad", "Grad")
                        .WithMany("Oglasi")
                        .HasForeignKey("GradId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookMarketplace.Model.Korisnik", "Korisnik")
                        .WithMany("Oglasi")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grad");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("BookMarketplace.Model.Poruka", b =>
                {
                    b.HasOne("BookMarketplace.Model.Oglas", "Oglas")
                        .WithMany("Poruke")
                        .HasForeignKey("OglasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookMarketplace.Model.Korisnik", "Posiljatelj")
                        .WithMany("PoslanePoruke")
                        .HasForeignKey("PosiljateljId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookMarketplace.Model.Korisnik", "Primatelj")
                        .WithMany("PrimljenePoruke")
                        .HasForeignKey("PrimateljId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Oglas");

                    b.Navigation("Posiljatelj");

                    b.Navigation("Primatelj");
                });

            modelBuilder.Entity("BookMarketplace.Model.Slika", b =>
                {
                    b.HasOne("BookMarketplace.Model.Oglas", "Oglas")
                        .WithMany("Slike")
                        .HasForeignKey("OglasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oglas");
                });

            modelBuilder.Entity("BookMarketplace.Model.Grad", b =>
                {
                    b.Navigation("Oglasi");
                });

            modelBuilder.Entity("BookMarketplace.Model.Korisnik", b =>
                {
                    b.Navigation("Favoriti");

                    b.Navigation("Oglasi");

                    b.Navigation("PoslanePoruke");

                    b.Navigation("PrimljenePoruke");
                });

            modelBuilder.Entity("BookMarketplace.Model.Oglas", b =>
                {
                    b.Navigation("DrustvenaIgra");

                    b.Navigation("Favoriti");

                    b.Navigation("Knjiga");

                    b.Navigation("Poruke");

                    b.Navigation("Slike");
                });
#pragma warning restore 612, 618
        }
    }
}
